import Link from 'next/link';

const SECTIONS = [
  {
    title: 'Agreement',
    body: [
      'By accessing or using StarlingPost, you agree to be bound by these Terms of Service.',
      'If you do not agree to these Terms, do not use the service.',
      'You must be at least 13 years old to use StarlingPost.',
    ],
  },
  {
    title: 'Use of service',
    body: [
      'You are responsible for all activity that occurs under your account.',
      'You are responsible for complying with the terms of service of each social media platform you connect through StarlingPost.',
      'You must provide accurate information when creating your account.',
      'You may not share account credentials or allow others to access your account.',
    ],
  },
  {
    title: 'Acceptable use',
    body: [
      'You agree not to use StarlingPost to send spam, unsolicited messages, or content that violates any applicable law.',
      'You agree not to use automation features to harass, abuse, or impersonate other users.',
      'You agree not to attempt to reverse-engineer, decompile, or otherwise extract the source code of StarlingPost.',
      'You agree not to use the service in a way that could damage, disable, or overburden our infrastructure.',
    ],
  },
  {
    title: 'Connected accounts',
    body: [
      'When you connect a social media account, you grant StarlingPost limited access to post, read, and interact with content on your behalf.',
      'You can revoke this access at any time by disconnecting the account from your dashboard or directly through the platform\'s app settings.',
      'We store OAuth access tokens but never your platform passwords.',
    ],
  },
  {
    title: 'AI features',
    body: [
      'AI-enhanced captions and auto-replies are generated by OpenAI\'s API. You are responsible for reviewing and approving AI-generated content before it is published.',
      'We do not guarantee the accuracy, quality, or appropriateness of AI-generated content.',
      'Content you submit to AI features may be processed by OpenAI subject to their usage policies.',
    ],
  },
  {
    title: 'Subscription and billing',
    body: [
      'The free tier is available at no cost and has no expiry.',
      'Pro tier subscriptions are billed monthly. Billing integration is in progress — no charges are currently processed.',
      'When billing is live: you may cancel at any time and will retain Pro access until the end of your paid period.',
    ],
  },
  {
    title: 'No warranty',
    body: [
      'StarlingPost is provided "as is" without warranties of any kind, express or implied.',
      'We do not guarantee uninterrupted uptime or that third-party platform APIs will remain available.',
      'Third-party APIs (YouTube, Twitter/X, LinkedIn, Meta) are outside our control and may change or be revoked at any time.',
    ],
  },
  {
    title: 'Limitation of liability',
    body: [
      'To the maximum extent permitted by applicable law, StarlingPost\'s liability is limited to the amount you paid for the service in the preceding 3 months.',
      'We are not liable for indirect, incidental, special, or consequential damages arising from your use of the service.',
    ],
  },
  {
    title: 'Changes to these terms',
    body: [
      'We may update these Terms from time to time.',
      'If changes are material, we will notify you within the app or by email at least 14 days before the changes take effect.',
      'Continued use of StarlingPost after the effective date constitutes acceptance of the new Terms.',
    ],
  },
  {
    title: 'Contact',
    body: [
      'Questions about these Terms: support@starlingpost.com.',
    ],
  },
];

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#0a0a0b] grain pt-20">
      <div className="max-w-[780px] mx-auto px-6 md:px-10 py-20">

        {/* Header */}
        <div className="mb-16 border-b border-stone-800 pb-12">
          <p className="font-mono text-[10px] uppercase tracking-[0.3em] text-stone-500 mb-4">Legal</p>
          <h1
            className="font-display italic text-stone-100 leading-none mb-4"
            style={{ fontSize: 'clamp(2.5rem, 6vw, 4.5rem)', fontVariationSettings: '"opsz" 144' }}
          >
            Terms of Service
          </h1>
          <p className="font-mono text-[10px] uppercase tracking-[0.2em] text-stone-600">
            Effective date: 1 March 2025 · Last updated: 12 May 2025
          </p>
        </div>

        {/* Intro */}
        <p className="text-stone-400 text-sm leading-relaxed mb-12">
          These Terms of Service govern your use of StarlingPost and all related services
          provided by StarlingPost (&quot;we&quot;, &quot;our&quot;, &quot;us&quot;) at starlingpost.com.
        </p>

        {/* Sections */}
        <div className="space-y-0 border border-stone-800">
          {SECTIONS.map((s, idx) => (
            <div key={s.title} className={`px-8 py-8 ${idx < SECTIONS.length - 1 ? 'border-b border-stone-800' : ''}`}>
              <h2
                className="font-display italic text-stone-100 mb-5"
                style={{ fontSize: '1.25rem', fontVariationSettings: '"opsz" 80' }}
              >
                {s.title}
              </h2>
              <ul className="space-y-3">
                {s.body.map((point, i) => (
                  <li key={i} className="flex items-start gap-3">
                    <span className="w-1 h-1 rounded-full bg-stone-700 mt-2 flex-shrink-0" />
                    <p className="text-stone-400 text-sm leading-relaxed">{point}</p>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        {/* Footer nav */}
        <div className="mt-12 pt-8 border-t border-stone-800 flex items-center justify-between">
          <Link href="/privacy" className="font-mono text-[10px] uppercase tracking-[0.2em] text-stone-500 hover:text-stone-200 transition-colors">
            Privacy policy →
          </Link>
          <Link href="/" className="font-mono text-[10px] uppercase tracking-[0.2em] text-stone-500 hover:text-stone-200 transition-colors">
            ← Home
          </Link>
        </div>

      </div>
    </main>
  );
}
