// lib/countryCodes.ts
export const COUNTRY_CODES = [
  { code: 'IN', dialCode: '+91', label: 'India' },
  { code: 'US', dialCode: '+1', label: 'United States' },
  { code: 'GB', dialCode: '+44', label: 'United Kingdom' },
  { code: 'AU', dialCode: '+61', label: 'Australia' },
  { code: 'AE', dialCode: '+971', label: 'United Arab Emirates' },
  { code: 'CA', dialCode: '+1', label: 'Canada' },
  { code: 'DE', dialCode: '+49', label: 'Germany' },
  { code: 'FR', dialCode: '+33', label: 'France' },
  { code: 'SG', dialCode: '+65', label: 'Singapore' },
  { code: 'BR', dialCode: '+55', label: 'Brazil' },
  { code: 'ZA', dialCode: '+27', label: 'South Africa' },
  { code: 'JP', dialCode: '+81', label: 'Japan' },
  { code: 'NZ', dialCode: '+64', label: 'New Zealand' },
  { code: 'HK', dialCode: '+852', label: 'Hong Kong' },
  { code: 'MY', dialCode: '+60', label: 'Malaysia' },
  { code: 'ID', dialCode: '+62', label: 'Indonesia' },
  { code: 'PH', dialCode: '+63', label: 'Philippines' },
  { code: 'TH', dialCode: '+66', label: 'Thailand' },
  { code: 'SA', dialCode: '+966', label: 'Saudi Arabia' },
  { code: 'RU', dialCode: '+7', label: 'Russia' },
  { code: 'CN', dialCode: '+86', label: 'China' },
  { code: 'IT', dialCode: '+39', label: 'Italy' },
  { code: 'ES', dialCode: '+34', label: 'Spain' },
  { code: 'NL', dialCode: '+31', label: 'Netherlands' },
  { code: 'SE', dialCode: '+46', label: 'Sweden' },
  { code: 'NO', dialCode: '+47', label: 'Norway' },
  { code: 'FI', dialCode: '+358', label: 'Finland' },
  { code: 'CH', dialCode: '+41', label: 'Switzerland' },
  { code: 'DK', dialCode: '+45', label: 'Denmark' },
  { code: 'BE', dialCode: '+32', label: 'Belgium' },
  { code: 'IE', dialCode: '+353', label: 'Ireland' },
  { code: 'PK', dialCode: '+92', label: 'Pakistan' },
  { code: 'BD', dialCode: '+880', label: 'Bangladesh' },
  { code: 'LK', dialCode: '+94', label: 'Sri Lanka' },
  { code: 'NP', dialCode: '+977', label: 'Nepal' },
  { code: 'AF', dialCode: '+93', label: 'Afghanistan' },
  { code: 'NG', dialCode: '+234', label: 'Nigeria' },
  { code: 'KE', dialCode: '+254', label: 'Kenya' },
  { code: 'GH', dialCode: '+233', label: 'Ghana' },
  { code: 'MX', dialCode: '+52', label: 'Mexico' },
  { code: 'AR', dialCode: '+54', label: 'Argentina' },
  { code: 'CL', dialCode: '+56', label: 'Chile' },
  { code: 'CO', dialCode: '+57', label: 'Colombia' },
  { code: 'TR', dialCode: '+90', label: 'Turkey' },
  { code: 'IL', dialCode: '+972', label: 'Israel' },
  { code: 'KR', dialCode: '+82', label: 'South Korea' },
  { code: 'TW', dialCode: '+886', label: 'Taiwan' },
  { code: 'PL', dialCode: '+48', label: 'Poland' },
  { code: 'PT', dialCode: '+351', label: 'Portugal' },
  { code: 'CZ', dialCode: '+420', label: 'Czech Republic' },
  { code: 'AT', dialCode: '+43', label: 'Austria' },
  // add more gradually as needed
];
